{
	"State":"Delhi",
	"Year":"2017",
	"Single-Classroom Schools":"0.01",
	"Single-Teacher Schools": "0.01",
	"Schools with Building" : "1",
	"Schools with Girls Toilet" : ".95",
	"Schools with Boys Toilet" :".99",
	"Schools with Toilet for CWSN" :".65",
	"Schools with Drinking Water": ".85",
	"Schools with Electricity": ".87",
	"Schools with Ramp if Needed": ".67",
	"Schools with Library": ".99",
	"Schools with Full time Librarian": ".97",
	"Schools with Boundary wall": ".95",
	"Schools Exclusively for CWSN": ".02",
	"Schools with Lab. Assistant": ".59",
	"Schools with Head Master Room": ".89",
	"Schools with Hostel for Boys":".79",
	"Schools with Hostel for Girls":".65",
	"Schools with Computer & Internet": ".95",
	"Schools with ICT Laboratory":".59",
	"Schools with Playground Facility": ".38",
	"Schools Conducted Med. Check-up": ".95",
	"Schools Having SMDC": ".68",
	"Schools with Sch. Bld. Committee": ".84",
	"Schools Having PTA": ".95",
	"Schools Established Since 2006": ".05",
	"Pupil-Teacher Ratio": "16.1",
	"Student-Classroom Ratio": "42.3",
	"Female Teachers": ".47",
	"Girls Enrolment":".48"
}
